version: "3.9"
services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heat_tracker
      MYSQL_USER: heat
      MYSQL_PASSWORD: heat
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: heat
      POSTGRES_PASSWORD: heat
      POSTGRES_DB: heat_tracker
    ports:
      - "5432:5432"
